apiVersion: apps/v1
kind: Deployment
metadata:
  name: light-controller-frontend
spec:
  selector:
    matchLabels:
      app: light-controller-frontend
  template:
    metadata:
      labels:
        app: light-controller-frontend
    spec:
      containers:
        - name: light-controller-frontend
          image: light-controller-frontend
          ports:
            - containerPort: 5173
          env:
            - name: VITE_API_URL
              value: "http://light-controller-backend:8080"
---
apiVersion: v1
kind: Service
metadata:
  name: light-controller-frontend
spec:
  selector:
    app: light-controller-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5173
  type: ClusterIP
